name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Start LocalStack with Docker Compose
        run: docker-compose up -d
      - name: Wait for LocalStack to be ready
        run: |
            echo "Waiting for LocalStack startup..."
            timeout 60 bash -c 'until curl -s http://localhost:4566/_localstack/health; do echo "Waiting..."; sleep 2; done'
            echo "LocalStack is ready!"
      - name: Print LocalStack logs on failure
        if: failure()
        run: docker logs integration_aws_test
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: | 
          pylint --fail-under 7 app
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"
      - name: Run integration tests
        env:
          PYTHONPATH: .
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pytest --maxfail=1 --disable-warnings -v
          coverage run -m pytest && coverage report -m
      - name: Teardown Docker
        if: always()
        run: docker-compose down
